api_platform:
    # title of th API.
    title:
        bletflix-api
    # The description of the API.
    description:
        'streaming online'

    # The version of the API.
    version: '1.2.0'

    # Set this to false if you want Webby to disappear.
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            bearer:
                name: Authorization
                type: header

    collection:
        # The name of the query parameter to filter nullable results (with the ExistsFilter).
        exists_parameter_name: 'exists'

        # The default order of results.
        order: 'ASC'

        # The name of the query parameter to order results (with the OrderFilter).
        order_parameter_name: 'order'

        pagination:
            # To enable or disable pagination for all resource collections by default.
            enabled: true

            # To allow the client to enable or disable the pagination.
            client_enabled: true

            # To allow the client to set the number of items per page.
            client_items_per_page: true

            # The default number of items per page.
            items_per_page: 30

            # The maximum number of items per page.
            maximum_items_per_page: 30

            # The default name of the parameter handling the page number.
            page_parameter_name: 'page'

            # The name of the query parameter to enable or disable pagination.
            enabled_parameter_name: 'pagination'

            # The name of the query parameter to set the number of items per page.
            items_per_page_parameter_name: 'itemsPerPage'

            # To allow partial pagination for all resource collections.
            # This improves performances by skipping the `COUNT` query.
            partial: false

            # To allow the client to enable or disable the partial pagination.
            client_partial: false

            # The name of the query parameter to enable or disable the partial pagination.
            partial_parameter_name: 'partial' # Default value

